[phases.setup]
nixPkgs = ["php82", "php82Extensions.intl", "php82Extensions.mbstring", "php82Extensions.mysqli"]
 
[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "cp env .env"
]
 
[start]
cmd = "sh -c 'php -S 0.0.0.0:$PORT -t public/'"
 
